<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ProjectType>ProgramLibrary</ProjectType>
	</PropertyGroup>
	<!-- Plugin-specific values; shared values (Version, Copyright, Company, ...) are in Directory.Build.props -->
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<RootNamespace>PepperDash.Essentials.Plugins.MakeModel</RootNamespace>
		<Deterministic>false</Deterministic>
		<AssemblyTitle>PepperDash.Essentials.Plugins.Make.Model</AssemblyTitle>
		<Description>This software is a PepperDash Essentials Plugin for a Make Model device.</Description>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<PackageId>PepperDash.Essentials.Plugins.Make.Model</PackageId>
		<PackageProjectUrl>https://github.com/PepperDash/epi-make-model</PackageProjectUrl>
		<PackageTags>crestron 4series essentials plugin</PackageTags>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants);SERIES4</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="epi-make-model.projectinfo" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="PepperDashEssentials" Version="2.42.4">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
